# Generated by Django 3.1.4 on 2021-01-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_attendance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateTimeField(),
        ),
    ]
